spring:
  application:
    name: NewsDaily
  profiles:
    include:
      #      - prod
      - local
  datasource:
    url: ${news.db.url}
    username: ${news.db.username:}
    password: ${news.db.password:}
  liquibase:
    contexts: ${news.liquibase.contexts:}
  h2:
    console:
      enabled: ${h2.console.enabled:false}
  jpa:
    hibernate:
      ddl-auto: update # make this property none if you want to retain your data in the database
logging:
  level:
    sql: debug
#    web: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always