spring:
  profiles:
    include: local
  application:
    name: newsapp
  datasource:
    url: ${newsapp.db.url}
    username: ${newsapp.db.username}
    password: ${newsapp.db.password}

logging:
  level:
    sql: debug
    '[org.springframework.web.servlet.DispatcherServlet]': debug
    '[org.springframework.web.client.RestTemplate]': debug
    '[com.orion.newsdaily]': debug
